sudo: required

language: node_js
node_js:
  - 10.13.0

on:
  -branch: master

before_install:
  - node -v
  - npm -v
  - yarn -v

script:
  - yarn run build:frontend
  - yarn run build:backend
  - yarn test