sudo: required

language: node_js
node_js:
  - 10.13.0

on:
  -branch: master

before_install:
  - node -v
  - npm -v
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - yarn -v

install:
  - yarn install --forzen-lockfile

script:
  - yarn run build:frontend
  - yarn run build:backend
  - yarn test