export const LogCons = {
  LOGIN: 'LOGIN',
  LOGSUCCESS: 'LOG_SUCCESS',
  LOGOUT: 'LOG_OUT',
  LOGFAIL: 'LOG_FAIL',
  AUTH_FAIL: 'AUTH_FAIL',
}

export const PostCons = {
  POST_CREATE: 'POST_CREATE',
  POST_SUCCESS: 'POST_SUCCESS',
  POST_FAIL: 'POST_FAIL',
  DELETE_POST: 'DELETE_POST',
  CLEAR_ACTION: 'CLEAR_ACTION',
  DELETE_SUCCESS: 'DELETE_SUCCESS',
}