export const LogCons = {
  LOGIN: 'LOGIN',
  LOGSUCCESS: 'LOG_SUCCESS',
  LOGOUT: 'LOG_OUT',
  LOGFAIL: 'LOG_FAIL',
}

export const PostCons = {
  POST_CREATE: 'POST_CREATE',
  POST_SUCCESS: 'POST_SUCCESS',
  POST_FAIL: 'POST_FAIL',
}