export const LogCons = {
  LOGIN: 'LOGIN',
  LOGSUCCESS: 'LOG_SUCCESS',
  LOGOUT: 'LOG_OUT',
  LOGFAIL: 'LOG_FAIL',
  AUTH_FAIL: 'AUTH_FAIL',
  CLEAR_AUTH: 'CLEAR_AUTH',
}

export const PostCons = {
  POST_CREATE: 'POST_CREATE',
  POST_SUCCESS: 'POST_SUCCESS',
  POST_FAIL: 'POST_FAIL',
  DELETE_POST: 'DELETE_POST',
  CLEAR_ACTION: 'CLEAR_ACTION',
  DELETE_SUCCESS: 'DELETE_SUCCESS',
}

export const UserCons = {
  FETCH_USER: 'FETCH_USER',
  FETCH_SUCCESS: 'FETCH_SUCCESS',
  EDIT_USER: 'EDIT_USER',
  FETCH_FAILED: 'FETCH_FAILED',
}